version: '3.8'

services:
  cafe-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cafe
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: cafe-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: